
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int comsimp = 9;
  public static final int suma = 14;
  public static final int ampersand = 8;
  public static final int rango = 35;
  public static final int minus = 38;
  public static final int coma = 15;
  public static final int llaveder = 34;
  public static final int igual = 22;
  public static final int identificador = 39;
  public static final int cadenasc = 40;
  public static final int guion = 16;
  public static final int parder = 11;
  public static final int numeral = 5;
  public static final int mayorque = 23;
  public static final int diagonalinv = 27;
  public static final int porcentaje = 7;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int corcheteizq = 26;
  public static final int apostrofe = 31;
  public static final int entero = 36;
  public static final int barra = 33;
  public static final int mayus = 37;
  public static final int doblepto = 19;
  public static final int punto = 17;
  public static final int comdob = 4;
  public static final int menorque = 21;
  public static final int potencia = 29;
  public static final int guionbajo = 30;
  public static final int nuevalinea = 10;
  public static final int conj = 2;
  public static final int llaveizq = 32;
  public static final int arroba = 25;
  public static final int dolar = 6;
  public static final int asterisco = 13;
  public static final int parizq = 12;
  public static final int admiracion = 3;
  public static final int ptocoma = 20;
  public static final int corcheteder = 28;
  public static final int interrogacion = 24;
  public static final int diagonal = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "conj",
  "admiracion",
  "comdob",
  "numeral",
  "dolar",
  "porcentaje",
  "ampersand",
  "comsimp",
  "nuevalinea",
  "parder",
  "parizq",
  "asterisco",
  "suma",
  "coma",
  "guion",
  "punto",
  "diagonal",
  "doblepto",
  "ptocoma",
  "menorque",
  "igual",
  "mayorque",
  "interrogacion",
  "arroba",
  "corcheteizq",
  "diagonalinv",
  "corcheteder",
  "potencia",
  "guionbajo",
  "apostrofe",
  "llaveizq",
  "barra",
  "llaveder",
  "rango",
  "entero",
  "mayus",
  "minus",
  "identificador",
  "cadenasc"
  };
}

